### PR TITLE
Fix panic when using LockFreeImmortalSpace for NoGC

### LINKED ISSUE #430: LockFreeImmortalSpace panics
An example crash can be found here. https://github.com/mmtk/ci-perf-result/blob/self-hosted/mutator/wrench-2021-08-20-Fri-195256/luindex.6000.132.jdk-mmtk-no-zeroing-nogc.ms.s.c2.tph.xmx8000M.xms8000M.rmmtkprobe.log.gz

```
mkdir -p /tmp/runbms-gitlab-runner 2>/dev/null; cd /tmp/runbms-gitlab-runner; /home/gitlab-runner/actions-runner/_work/mmtk-core/mmtk-core/ci-perf-kit/running/bin/timedrun -t 240 /home/gitlab-runner/actions-runner/_work/mmtk-core/mmtk-core/ci-perf-kit/running/build/jdk-mmtk-no-zeroing-nogc/jdk/bin/java -Xmx8000M -Xms8000M -XX:MetaspaceSize=100M -server -XX:-TieredCompilation -XX:+UseThirdPartyHeap -Dprobes=RustMMTk -Djava.library.path=/home/gitlab-runner/actions-runner/_work/mmtk-core/mmtk-core/ci-perf-kit/running/../probes/rust_mmtk -cp /home/gitlab-runner/actions-runner/_work/mmtk-core/mmtk-core/ci-perf-kit/running/../probes/probes.jar:/home/gitlab-runner/actions-runner/_work/mmtk-core/mmtk-core/ci-perf-kit/running/../probes/rust_mmtk/java:/home/gitlab-runner/actions-runner/_work/mmtk-core/mmtk-core/ci-perf-kit/running/../probes/openjdk/java:/usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar Harness -c probe.Dacapo2006Callback -n 2 luindex 
OS: Linux wrench 5.4.0-80-generic #90~18.04.1-Ubuntu SMP Tue Jul 13 19:40:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
cpu: model name	: AMD Ryzen 9 3900X 12-Core Processor
number of cores: 24
Warn: unable to set plan="semispace". Cant parse value. Default value will be used.
thread '<unnamed>' panicked at 'not implemented', /home/gitlab-runner/actions-runner/_work/mmtk-core/mmtk-core/mmtk-openjdk/repos/mmtk-core/src/policy/lockfreeimmortalspace.rs:74:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
```

The cause appears to be this https://github.com/mmtk/mmtk-core/blob/e581539/src/policy/lockfreeimmortalspace.rs#L73

### PR DESCRIPTION
**Pull request by caizixian**
Closes #430 

LockFreeImmortalSpace doesn't have a common space, and various functions try to get the common space.
This PR overrides some of the default behaviours to avoid the runtime panic.

### CODE REVIEW

File: src/plan/nogc/global.rs [hunk 1]
```diff
@@ -144,8 +144,10 @@ impl<VM: VMBinding> NoGC<VM> {
         let mut side_metadata_sanity_checker = SideMetadataSanity::new();
         res.base
             .verify_side_metadata_sanity(&mut side_metadata_sanity_checker);
-        res.nogc_space
-            .verify_side_metadata_sanity(&mut side_metadata_sanity_checker);
+        if cfg!(not(feature = "nogc_lock_free")) {
+            res.nogc_space
+                .verify_side_metadata_sanity(&mut side_metadata_sanity_checker);
```
Comment (qinsoon) [inline src/plan/nogc/global.rs:149]: Will it be better if we override `verify_side_metadata_sanity()` for `LockFreeImmortalSpace` rather than skipping the verification? For example, `MallocSpace` does not use `CommonSpace`, but it implements `verify_side_metadata_sanity`.

**Review by qinsoon — APPROVED** [review]
LGTM. Though I think for `verify_side_metadata_sanity`, we should override it rather than skipping it.

File: src/plan/nogc/global.rs (hunk 1 above)
Comment (caizixian) [reply src/plan/nogc/global.rs]: Fixed. Please take a look.

**Comment by qinsoon** [comment]
I will look at this tomorrow, and possibly I will push some changes to the PR.

**Comment by qinsoon** [comment]
I have pushed a commit that the overriden implementation of `verify_side_metadata_sanity()` will call the side metadata sanity checker properly. You may want to test this and see if it is working as expected (in my tests, it works fine). If you think the change is okay, we can merge this PR. @caizixian
